apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: nodestorage #it will map your pvc with pv
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
